/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'itemId' : string,
  'paid' : boolean,
  'orderTime' : bigint,
  'quantity' : bigint,
  'customerId' : Principal,
  'totalPrice' : bigint,
}
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'vendorId' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface ProductInput {
  'name' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
}
export interface TrendingProduct {
  'productId' : string,
  'purchaseCount' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : string,
  'productsCount' : bigint,
  'contact' : string,
  'revenue' : bigint,
  'company' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addProductWithoutVendor' : ActorMethod<[ProductInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkOut' : ActorMethod<[Principal], undefined>,
  'deleteProduct' : ActorMethod<[string, string], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProductsByVendorId' : ActorMethod<[string], Array<Product>>,
  'getProductsFromAdmin' : ActorMethod<[], Array<Product>>,
  'getTrendingProducts' : ActorMethod<[], Array<TrendingProduct>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendor' : ActorMethod<[string], [] | [Vendor]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'kvDelete' : ActorMethod<[string], undefined>,
  'kvGet' : ActorMethod<[string], [] | [string]>,
  'kvGetAll' : ActorMethod<[], Array<[string, string]>>,
  'kvSet' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];